language: node_js
node_js:
- '0.11'
deploy:
  provider: heroku
  app:
    master:
      secure: VFy6VXd9q+mMrbk+Sgyvt52Fpq2YrUHkixiKrK1bn1Av0fDquvCnDnmxEft05psv3OYqA0FTRa1lBfZk3tmjQNiaI0hRp0JRs3jh2yDcnAb5WzHe2NjQrMxz6M46S61gyU1nVRnMdIk+chrLFT4vBL1FuoYRhKtyl0h9FtVRPU0=
  api_key:
    secure: NCfQTRa+D2i81Zzx64TinDRnHImPg2z/6R6j+uM8YZKS3f8KrdHfFUAOPtyBaa7+THq9YYo0QkN/uD4/dmBo897yIefbvwGOeE9pqelc/dnkJD64ZQ3nnsCcf09FaRKVJvfp/3CKdHybpaEggBf5gKBQhKUj9B3zgSnSOBV8jnM=
